### ISSUE TITLE
Error when running synthetic example line: FileNotFoundError: [Errno 2] No such file or directory: 'crl/envelope/logs/m.linear_e.ft_n.0.log'

### ISSUE THREAD

**Issue by kasimte** [RunzheYang/MORL#1]
I get the following errors when running the synthetic example line from the README. Is this an issue with my environment?

Environment:

* Python 3.7
* Installed numpy, torch, visdom.

Error log:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Kasim/opt/anaconda3/envs/morl/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/Kasim/opt/anaconda3/envs/morl/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/Kasim/opt/anaconda3/envs/morl/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x123635fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Kasim/opt/anaconda3/envs/morl/lib/python3.7/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/Users/Kasim/opt/anaconda3/envs/morl/lib/python3.7/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/Users/Kasim/opt/anaconda3/envs/morl/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/Kasim/opt/anaconda3/envs/morl/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Kasim/opt/anaconda3/envs/morl/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Kasim/opt/anaconda3/envs/morl/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x123635fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
Traceback (most recent call last):
  File "train.py", line 155, in <module>
    train(env, agent, args)
  File "train.py", line 60, in train
    monitor.init_log(args.log, "m.{}_e.{}_n.{}".format(args.model, args.env_name, args.name))
  File "/Users/Kasim/Projects/ml/MORL/synthetic/utils/monitor.py", line 54, in init_log
    self.log_file = open("{}{}.log".format(save_path, name), 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'crl/envelope/logs/m.linear_e.ft_n.0.log'
```

**Comment by RunzheYang** [comment]
Regarding the running error, you may need to create two folders `crl/naive/logs/` and `crl/envelope/logs/` for saving log files, and also `crl/naive/saved/` and `crl/envelope/saved/` for saving trained models.

**Comment by kasimte** [comment]
Thanks, @RunzheYang ! I created the suggested directories and have the synthetic example code line running now.
